apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /var/nfs/shared
    server: <NFS_SERVER_IP>
  storageClassName: nfs-storage-class
